---
- name: set password for the postgres user
  become_user: postgres
  community.postgresql.postgresql_user:
    login_unix_socket: /tmp
    login_port: "{{  item.value.port }}"
    name: postgres
    password: "{{ postgres_db_user_pass }}"
  loop: "{{ postgres_db_dir_port | dict2items }}"
  when: postgres_db_user == true

- name: create user for replication
  community.postgresql.postgresql_user:
    login_unix_socket: /tmp
    name: "{{ postgres_db_rep_role }}"
    password: "{{ postgres_db_rep_role_pass }}"
    role_attr_flags: "REPLICATION"
  loop: "{{ postgres_db_dir_port | dict2items }}"
  when: postgres_db_rep_slot == true and inventory_replica_signal == false

- name: 'create ~/.pgpass'
  become_user: postgres
  template:
    src: templates/.pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    mode: 0600
