---
# tasks file for postgres
- name:  Check postgres for 1C is installed
  stat:
    path: /opt/pgpro/1c-{{ postgres_pg_ver }} 
  register: pg_installed
  when: postgres_pg_1c == true

- name: Check posgres for 1C gpg key is exist
  stat:
    path: "/etc/apt/trusted.gpg.d/pg_for1c-{{ postgres_db_data }}.asca"
  register: pg_gpg_key

- name: install gpg_key postgrespro
  get_url:
    url: https://repo.postgrespro.ru/keys/GPG-KEY-POSTGRESPRO
    dest: /etc/apt/trusted.gpg.d/pg_for1c.asc
  when: pg_gpg_key.stat.exists == false and postgres_pg_1c == true

- name: add repo for postgres for 1c
  apt_repository:
    repo: deb [arch=amd64] https://repo.postgrespro.ru/1c/1c-{{ postgres_pg_ver }}/ubuntu {{ ansible_distribution_release }} main
  when: postgres_pg_1c == true and pg_installed.stat.exists == false

- name: install postgres-{{ postgres_pg_ver }}
  apt:
    update_cache: true
    pkg:
      - "{{ pg_install }}"
      - acl
      - python3-pip
    state: present
  vars: 
    pg_install: "{{ 'postgrespro-1c-' + postgres_pg_ver + '-contrib' if postgres_pg_1c | bool else 'postgresql-' + postgres_pg_ver }}"
  tags: replica

- name: Ensure a locales exists
  locale_gen:
    name: 
      - ru_RU.UTF-8
      - en_US.UTF-8
    state: present
  tags: replica
 
- name: ensure psycopg2-binary is install
  pip:
    name: psycopg2-binary
    state: present
  tags: replica

- name: initdb and createuser
  block:
    - import_tasks: initdb.yml
    - import_tasks: service.yml
    - import_tasks: create_user.yml

#create replica slot if postgres_db_rep_slot true
- name: replication
  ansible.builtin.include_tasks:
    file: replica.yml
  tags: replica
  when: inventory_replica_signal == true

